name: Auto Deploy

on:
  push:
    branches:
      - main # ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # Branch onde será publicado
          folder: . # Pasta que contém os arquivos
          token: ${{ secrets.GITHUB_TOKEN }}
